import { Controller, HttpCode, HttpStatus, Post, UploadedFiles, UseInterceptors } from '@nestjs/common';
import { FilesInterceptor } from '@nestjs/platform-express';
import { ApiBody, ApiConsumes, ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { AuditService } from './audit.service.js';
import { AuditReportDto } from './dto/audit-report.dto.js';

@ApiTags('audit')
@Controller('audit')
export class AuditController {
  constructor(private readonly auditService: AuditService) {}

  @Post()
  @HttpCode(HttpStatus.OK)
  // No local options here on purpose — they would override (not merge with) the
  // storage/limits injected via MulterModule.registerAsync in AuditModule.
  @UseInterceptors(FilesInterceptor('files'))
  @ApiOperation({
    summary: 'Run an AI-powered security audit over one or more uploaded files',
    description:
      'Accepts any number of text-based files (source code, IaC, server configs, CI/CD pipelines, env files) and returns a structured vulnerability report generated by Gemini Flash.',
  })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      required: ['files'],
      properties: {
        files: {
          type: 'array',
          items: { type: 'string', format: 'binary' },
        },
      },
    },
  })
  @ApiResponse({ status: 200, description: 'Audit completed successfully.', type: AuditReportDto })
  @ApiResponse({
    status: 400,
    description: 'Invalid upload — no files, too many files, or a rejected file (unsafe path, binary content, or oversized).',
  })
  @ApiResponse({ status: 413, description: 'Total upload size exceeds the configured aggregate limit.' })
  @ApiResponse({ status: 429, description: 'Rate limit exceeded for this endpoint.' })
  @ApiResponse({ status: 502, description: 'Gemini returned a response that could not be used.' })
  @ApiResponse({ status: 503, description: 'Gemini API key is not configured, or the Gemini API is currently unavailable.' })
  async audit(@UploadedFiles() files: Express.Multer.File[]): Promise<AuditReportDto> {
    return this.auditService.runAudit(files);
  }
}
