import { Controller, Get, HttpCode, HttpStatus, Param, Post, Query, UploadedFiles, UseGuards, UseInterceptors } from '@nestjs/common';
import { FilesInterceptor } from '@nestjs/platform-express';
import { ApiBearerAuth, ApiBody, ApiConsumes, ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { AuthGuard } from '../auth/auth.guard.js';
import { CurrentUser } from '../auth/current-user.decorator.js';
import type { AuthenticatedUser } from '../auth/auth.types.js';
import { AuditService } from './audit.service.js';
import { AuditHistoryQueryDto } from './dto/audit-history-query.dto.js';
import { AuditReportDto } from './dto/audit-report.dto.js';
import { PaginatedAuditHistoryDto } from './dto/paginated-audit-history.dto.js';

@ApiTags('audit')
@ApiBearerAuth()
@UseGuards(AuthGuard)
@Controller('audit')
export class AuditController {
  constructor(private readonly auditService: AuditService) {}

  @Post()
  @HttpCode(HttpStatus.OK)
  // No local options here on purpose — they would override (not merge with) the
  // storage/limits injected via MulterModule.registerAsync in AuditModule.
  @UseInterceptors(FilesInterceptor('files'))
  @ApiOperation({
    summary: 'Run an AI-powered security audit over one or more uploaded files',
    description:
      'Accepts any number of text-based files (source code, IaC, server configs, CI/CD pipelines, env files), returns a structured vulnerability report generated by Gemini Flash, and saves it to the authenticated user\'s history.',
  })
  @ApiConsumes('multipart/form-data')
  @ApiBody({
    schema: {
      type: 'object',
      required: ['files'],
      properties: {
        files: {
          type: 'array',
          items: { type: 'string', format: 'binary' },
        },
      },
    },
  })
  @ApiResponse({ status: 200, description: 'Audit completed and saved successfully.', type: AuditReportDto })
  @ApiResponse({
    status: 400,
    description: 'Invalid upload — no files, too many files, or a rejected file (unsafe path, binary content, or oversized).',
  })
  @ApiResponse({ status: 401, description: 'Missing or invalid authentication.' })
  @ApiResponse({ status: 413, description: 'Total upload size exceeds the configured aggregate limit.' })
  @ApiResponse({ status: 429, description: 'Rate limit exceeded for this endpoint.' })
  @ApiResponse({ status: 502, description: 'Gemini returned a response that could not be used.' })
  @ApiResponse({ status: 503, description: 'Gemini API key is not configured, or the Gemini API is currently unavailable.' })
  async audit(@CurrentUser() user: AuthenticatedUser, @UploadedFiles() files: Express.Multer.File[]): Promise<AuditReportDto> {
    return this.auditService.runAudit(files, user.id);
  }

  @Get('history')
  @ApiOperation({ summary: "Paginated list of the authenticated user's past audits" })
  @ApiResponse({ status: 200, description: 'Paginated audit history.', type: PaginatedAuditHistoryDto })
  @ApiResponse({ status: 401, description: 'Missing or invalid authentication.' })
  async history(@CurrentUser() user: AuthenticatedUser, @Query() query: AuditHistoryQueryDto): Promise<PaginatedAuditHistoryDto> {
    return this.auditService.findHistory(user.id, query.page, query.limit);
  }

  @Get(':id')
  @ApiOperation({ summary: 'Fetch one full audit report (with findings) by id' })
  @ApiResponse({ status: 200, description: 'The full audit report.', type: AuditReportDto })
  @ApiResponse({ status: 400, description: 'The id is not a valid report id.' })
  @ApiResponse({ status: 401, description: 'Missing or invalid authentication.' })
  @ApiResponse({ status: 404, description: 'No report with this id belongs to the authenticated user.' })
  async findOne(@CurrentUser() user: AuthenticatedUser, @Param('id') id: string): Promise<AuditReportDto> {
    return this.auditService.findById(user.id, id);
  }
}
